FROM python:3.11-slim

RUN pip install --no-cache-dir \
    mysql-connector-python \
    sqlalchemy \
    pandas \
    tqdm \
    xxhash \
    redis \
    jupyterlab \
    ipython-sql

WORKDIR /app
CMD ["tail", "-f", "/dev/null"]
