CREATE DATABASE IF NOT EXISTS dedup_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE dedup_db;

CREATE TABLE IF NOT EXISTS file_metadata (
	id BIGINT UNSIGNED PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    full_path VARCHAR(2048) NOT NULL,
    hash1 VARCHAR(32) DEFAULT NULL,
    hash2 VARCHAR(32) DEFAULT NULL,
    hash3 VARCHAR(32) DEFAULT NULL,
    hash4 VARCHAR(32) DEFAULT NULL,
    hash5 VARCHAR(32) DEFAULT NULL,
    st_dev VARCHAR(32) DEFAULT NULL,
    st_ino VARCHAR(32) DEFAULT NULL,
    st_size BIGINT UNSIGNED DEFAULT 0,
    st_mtime DOUBLE DEFAULT 0,

    INDEX idx_size_prefix (st_dev, st_ino),
    INDEX idx_hash1 (st_size, hash1)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
